<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <Authors>Arash Jahangiri (@arashzjahangiri)</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/arashzjahangiri/CleanArch</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) 2023 Jean Francisco Flores Gatto</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>